# File: config/evaluated_llm_configs/mistral-7b-instruct.yaml

provider: vultr
api_key_env: VULTR_API_KEY
base_url: https://api.vultrinference.com/v1


model: mistral-nemo-instruct-2407
timeout_seconds: 30
max_retries: 3
rate_limit_sleep: 0.5

temperature: 0.0
max_tokens: 128
batch_size: 10