version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/app

  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    working_dir: /app
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app

volumes:
  pgdata: