services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
      POSTGRES_DB: benchmarkdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    working_dir: /app
    stdin_open: true
    tty: true
    env_file:
      - .env

volumes:
  pgdata: