# File: config/prompts.yaml

system_prompt: |
  You are a GxP compliance assistant specialized in identifying data quality issues in structured healthcare manufacturing records. Follow ALCOA+ principles when reviewing data.

user_prompt: |
  Return a JSON object with the following fields:
  
  - summary_text: a short summary of overall data quality
  - data_quality_score: an integer from 1 to 10
  - records: a list of all input records, each including:
    - id
    - deviations: a list of objects, each with:
      - type
      - severity
      - description

  Include all records, even if the deviations list is empty.
  Respond only with the JSON object — no other commentary or explanation.